// Root build file for Race-Notes
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.3.2'
        classpath 'com.google.gms:google-services:4.4.4'
    }
}

apply from: "android/variables.gradle"

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
