import { Setup, SessionRecord, ActiveSession, RaceWeekend } from './types';

export const INITIAL_SETUP: Setup = {
  id: '',
  chassis: '',
  track: '',
  date: '',
  carType: '',
  gear: '',
  frontStagger: '',
  rearStagger: '',
  pullBarFrameHole: '',
  pullBarRearHole: '',
  pullBarAngle: '',
  lf: {
    spring: '',
    shock: '',
    loadWeight: '',
    loadCtoC: '',
    caster: '',
    camber: '',
    tireComp: '',
    tireSize: '',
    toe: '',
    stagger: '',
    wheelSpacer: '',
    tirePress: '',
  },
  rf: {
    spring: '',
    shock: '',
    loadWeight: '',
    loadCtoC: '',
    caster: '',
    camber: '',
    tireComp: '',
    tireSize: '',
    toe: '',
    stagger: '',
    wheelSpacer: '',
    tirePress: '',
  },
  lr: {
    spring: '',
    springHeight: '',
    shock: '',
    load: '',
    loadCtoC: '',
    topBarHFrame: '',
    topBarHBird: '',
    topBarAngRH: '',
    topBarAngFD: '',
    botBarHFrame: '',
    botBarHBird: '',
    bottomBarAngle: '',
    droop: '',
    tireComp: '',
    tireSize: '',
    stagger: '',
    rearGear: '',
    pullBarHole: '',
    pullBarAngle: '',
    tirePress: '',
  },
  rr: {
    spring: '',
    springHeight: '',
    shock: '',
    load: '',
    loadCtoC: '',
    topBarHFrame: '',
    topBarHBird: '',
    topBarAngRH: '',
    topBarAngFD: '',
    botBarHFrame: '',
    botBarHBird: '',
    bottomBarAngle: '',
    droop: '',
    tireComp: '',
    tireSize: '',
    stagger: '',
    rearGear: '',
    pullBarHole: '',
    pullBarAngle: '',
    tirePress: '',
  }
};

export const INITIAL_SETUPS: Setup[] = [];

export const INITIAL_WEEKENDS: RaceWeekend[] = [];

export const INITIAL_RECENT_SESSIONS: SessionRecord[] = [];

export const INITIAL_ACTIVE_SESSION: ActiveSession = {
  name: '',
  track: '',
  setupUsed: '',
  condition: '',
  weather: '',
  time: '',
  bestLap: '',
  avgLap: '',
  finishPos: '',
  gap: '',
  maxRpm: '',
  leaderLap: '',
  leaderGap: '',
  diagnostics: {
    cornerEntry: 'NEUTRAL',
    cornerEntryNotes: '',
    centerApex: 'NEUTRAL',
    centerApexNotes: '',
    cornerExit: 'NEUTRAL',
    cornerExitNotes: '',
  },
  adjustments: [],
  tires: {
    lf: { tireId: '', compound: '', size: '', durometer: '', airPressure: '', backSpacing: '' },
    rf: { tireId: '', compound: '', size: '', durometer: '', airPressure: '', backSpacing: '' },
    lr: { tireId: '', compound: '', size: '', durometer: '', airPressure: '', backSpacing: '' },
    rr: { tireId: '', compound: '', size: '', durometer: '', airPressure: '', backSpacing: '' }
  },
  pressures: {
    lf: '',
    rf: '',
    lr: '',
    rr: '',
  },
  competitionNotes: '',
};

